### ISSUE TITLE
Proyecto en local diferente a resultado en ghpages.

### ISSUE THREAD

**Issue by oOBoniOo** [oOBoniOo/snake#15]
**Describe the bug**
El avance del proyecto en m pc local es diferente a lo que puedo visualizar cuando pruebo ghPages.

**Comment by amargopastor** [comment]
@oOBoniOo echo en falta una descripción más detallada del problema así como capturas de pantalla etc.

Por lo que entiendo, cuando ejecutas en local tu proyecto el resultado es distinto al de GitHub page. Prueba a revisar:

- Que tu código está correctamente guardado en local
- Que has hecho push de los commits realizados
- Que el código en github refleja tus últimos cambios
- Que no se trata de un problema de caché (prueba en incógnito)

Resultado actual en producción:
https://oobonioo.github.io/snake/
![Screenshot 2021-12-27 at 10 51 40](https://user-images.githubusercontent.com/73180300/147459632-abf2f139-0e3f-4cc4-9d8d-a3ebc9dab80c.png)
![Screenshot 2021-12-27 at 10 52 57](https://user-images.githubusercontent.com/73180300/147459746-9015b6a8-5eba-45a0-a374-20be919eb614.png)


Pd. Cambia el title de tu proyecto: figura canvas car II 😄
